[build]
builder = "NIXPACKS"
buildCommand = "cd Backend && npm install && npx prisma generate"

[deploy]
startCommand = "cd Backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
